# Generated by Django 5.2.12 on 2026-03-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('cultural', 'Cultural'), ('interior', 'Interiors'), ('renovation', 'Renovation')], default='residential', max_length=40),
        ),
    ]
