# Generated by Django 5.2.12 on 2026-03-26 10:05

from django.db import migrations, models

LEGACY_CATEGORY_MAP = {
    "residential": "housing",
    "commercial": "workplace",
    "cultural": "civic",
}
CANONICAL_CATEGORIES = {"housing", "civic", "workplace"}
UNSUPPORTED_LEGACY_CATEGORIES = {"interior", "renovation"}


def remap_project_categories(apps, schema_editor):
    Project = apps.get_model("projects", "Project")

    unsupported = sorted(
        set(
            Project.objects.filter(category__in=UNSUPPORTED_LEGACY_CATEGORIES)
            .values_list("category", flat=True)
            .distinct()
        )
    )
    if unsupported:
        joined = ", ".join(unsupported)
        raise RuntimeError(
            "Unsupported legacy project categories remain and must be manually "
            f"reclassified before this migration can run: {joined}"
        )

    for old_value, new_value in LEGACY_CATEGORY_MAP.items():
        Project.objects.filter(category=old_value).update(category=new_value)

    remaining_invalid = sorted(
        set(
            Project.objects.exclude(category__in=CANONICAL_CATEGORIES)
            .values_list("category", flat=True)
            .distinct()
        )
    )
    if remaining_invalid:
        joined = ", ".join(remaining_invalid)
        raise RuntimeError(
            "Project taxonomy migration expected only canonical categories after "
            f"remapping but found: {joined}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_clean_category_choices"),
    ]

    operations = [
        migrations.RunPython(remap_project_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("housing", "Housing"),
                    ("civic", "Civic"),
                    ("workplace", "Workplace"),
                ],
                default="housing",
                max_length=40,
            ),
        ),
    ]
