# Generated by Django 5.2.12 on 2026-04-12 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_simplify_project_taxonomy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project this testimonial is associated with. Testimonials without a project are stored but not rendered on any public page — only project-linked testimonials appear on project detail pages.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='projects.project'),
        ),
    ]
