# Generated by Django 5.2.12 on 2026-03-21 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(help_text='One or two clear sentences shown on project cards and in search results. Under 160 characters is ideal.', max_length=300)),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('cultural', 'Cultural'), ('mixed_use', 'Mixed Use'), ('interior', 'Interior Architecture'), ('concept', 'Conceptual'), ('renovation', 'Renovation & Adaptive Reuse'), ('competition', 'Competition'), ('other', 'Other')], default='other', max_length=40)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('concept', 'Concept'), ('competition', 'Competition Entry')], default='completed', max_length=20)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=150)),
                ('area', models.CharField(blank=True, help_text='e.g. "2 400 m²"', max_length=60)),
                ('services_provided', models.TextField(blank=True, help_text="Scope of services delivered, e.g. 'Concept design through construction administration.' One service per line.")),
                ('overview', models.TextField(blank=True, help_text='Project introduction paragraph.')),
                ('challenge', models.TextField(blank=True)),
                ('concept', models.TextField(blank=True)),
                ('process', models.TextField(blank=True, help_text='Optional — describe the design and construction process, methods used, or team collaboration.')),
                ('outcome', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Recommended: at least 1600 × 900 px, JPEG or WebP. Used as the hero image and OpenGraph share image.', null=True, upload_to='projects/covers/')),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, help_text='Overrides project title in browser tab and search results. Ideal length: under 60 characters.', max_length=70)),
                ('seo_description', models.CharField(blank=True, help_text='Overrides short description in search results. Under 160 characters.', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, default='', help_text='Descriptive alt text for screen readers. Falls back to caption if empty.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image_type', models.CharField(choices=[('gallery', 'Gallery'), ('plan', 'Floor Plan'), ('section', 'Section / Elevation'), ('sketch', 'Sketch'), ('detail', 'Detail'), ('render', 'Render')], default='gallery', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('quote', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='projects.project')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order'],
            },
        ),
    ]
