# Generated by Django 5.2.12 on 2026-03-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('project_type', models.CharField(blank=True, max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for admin workflow — not visible to the client.')),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
