# Generated by Django 5.2.12 on 2026-04-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_sitesettings_nav_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, help_text='Stored but not currently rendered on any public page. Reserved for future use or custom template additions.'),
        ),
    ]
