# Generated by Django 5.2.12 on 2026-04-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_sitesettings_services_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_compact',
            field=models.BooleanField(default=False, help_text='Compact hero text — use if your studio name or tagline is long and the hero looks crowded.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_label',
            field=models.CharField(blank=True, default='', help_text="Short descriptor shown above the studio name in the homepage hero (e.g. 'Design & Strategy'). Leave blank to omit.", max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_name',
            field=models.CharField(blank=True, default='', help_text='Overrides the automatic nav brand. Leave blank to let the system choose: short one- or two-word names (up to 18 characters) are shown in full; longer or multi-word names display as a derived monogram (e.g. ‘BWK’ for ‘Beaumont Whitfield Kellerman Partnership’). Set this field to an abbreviation like ‘Strand Studio’ or ‘BWK Partners’ if the automatic monogram is not what you want. A logo supersedes all text options.', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='', help_text="Your studio's display name. Shorter names (under 40 characters) work best in the homepage hero.", max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, default='Design shaped by purpose, context, and enduring quality.', help_text='One or two sentences describing your work. Under 140 characters fits most hero layouts cleanly.', max_length=220),
        ),
    ]
