# Generated by Django 5.2.12 on 2026-04-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_brand_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='blog_meta_description',
            field=models.CharField(blank=True, help_text='Meta description for the Blog list page. Falls back to the homepage meta description.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_meta_title',
            field=models.CharField(blank=True, help_text='Optional meta title for the Blog list page. Falls back to the page label.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portfolio_preset',
            field=models.CharField(choices=[('generic', 'Generic portfolio'), ('service', 'Service / consultant portfolio'), ('academic', 'Academic / research portfolio')], default='generic', help_text='Controls reusable homepage and navigation emphasis. Use Academic / research portfolio for researchers, PhD students, lecturers, scientists, consultants, and technical experts.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='publications_meta_description',
            field=models.CharField(blank=True, help_text='Meta description for the Publications page. Falls back to the homepage meta description.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='publications_meta_title',
            field=models.CharField(blank=True, help_text='Optional meta title for the Publications page. Falls back to the page label.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='research_meta_description',
            field=models.CharField(blank=True, help_text='Meta description for the Research page. Falls back to the homepage meta description.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='research_meta_title',
            field=models.CharField(blank=True, help_text='Optional meta title for the Research page. Falls back to the page label.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='resume_meta_description',
            field=models.CharField(blank=True, help_text='Meta description for the Resume / CV page. Falls back to the homepage meta description.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='resume_meta_title',
            field=models.CharField(blank=True, help_text='Optional meta title for the Resume / CV page. Falls back to the page label.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_meta_description',
            field=models.CharField(blank=True, help_text='Meta description for the Services page. Falls back to the homepage meta description.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_meta_title',
            field=models.CharField(blank=True, help_text='Optional meta title for the Services page. Falls back to the page label.', max_length=120),
        ),
    ]
