# Generated by Django 5.2.12 on 2026-03-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesettings_contact_email_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Years of professional experience. This value renders publicly — 0 is a placeholder; enter the real figure.'),
        ),
    ]
