# Generated by Django 5.1.15 on 2026-03-19 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=200)),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="Short intro paragraph shown at the top of the About page.",
                    ),
                ),
                ("biography", models.TextField(blank=True)),
                ("philosophy", models.TextField(blank=True)),
                (
                    "credentials",
                    models.TextField(
                        blank=True,
                        help_text="Education, certifications, memberships — one per line.",
                    ),
                ),
                ("experience_years", models.PositiveIntegerField(default=0)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("portrait", models.ImageField(blank=True, null=True, upload_to="about/")),
                ("cv_file", models.FileField(blank=True, null=True, upload_to="about/cv/")),
            ],
            options={
                "verbose_name": "About Profile",
                "verbose_name_plural": "About Profile",
            },
        ),
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(blank=True, max_length=150)),
                ("project_type", models.CharField(blank=True, max_length=150)),
                ("location", models.CharField(blank=True, max_length=150)),
                ("budget_range", models.CharField(blank=True, max_length=100)),
                ("timeline", models.CharField(blank=True, max_length=100)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                            ("archived", "Archived"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Inquiry",
                "verbose_name_plural": "Contact Inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "short_description",
                    models.CharField(
                        help_text="One punchy sentence shown in project cards.", max_length=300
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("cultural", "Cultural"),
                            ("mixed_use", "Mixed Use"),
                            ("interior", "Interior Architecture"),
                            ("concept", "Conceptual"),
                            ("renovation", "Renovation & Adaptive Reuse"),
                            ("competition", "Competition"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("in_progress", "In Progress"),
                            ("concept", "Concept"),
                            ("competition", "Competition Entry"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=150)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("client", models.CharField(blank=True, max_length=150)),
                ("area", models.CharField(blank=True, help_text='e.g. "2 400 m²"', max_length=60)),
                ("services_provided", models.TextField(blank=True)),
                (
                    "overview",
                    models.TextField(blank=True, help_text="Project introduction paragraph."),
                ),
                ("challenge", models.TextField(blank=True)),
                ("concept", models.TextField(blank=True)),
                ("process", models.TextField(blank=True)),
                ("outcome", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="projects/covers/"),
                ),
                ("featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["order", "-year", "title"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("summary", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True)),
                ("who_for", models.CharField(blank=True, max_length=250)),
                ("value_proposition", models.TextField(blank=True)),
                (
                    "deliverables",
                    models.TextField(blank=True, help_text="One deliverable per line."),
                ),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional icon identifier (e.g. 'pen-ruler', 'building').",
                        max_length=60,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("site_name", models.CharField(default="Jeannot Tsirenge", max_length=120)),
                (
                    "tagline",
                    models.CharField(
                        default="Architectural design shaped by context, clarity, and identity.",
                        max_length=220,
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="site/")),
                (
                    "contact_email",
                    models.EmailField(default="contact@jeannot-tsirenge.com", max_length=254),
                ),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("address", models.TextField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                ("google_analytics_id", models.CharField(blank=True, max_length=30)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("gallery", "Gallery"),
                            ("plan", "Floor Plan"),
                            ("section", "Section / Elevation"),
                            ("sketch", "Sketch"),
                            ("detail", "Detail"),
                            ("render", "Render"),
                        ],
                        default="gallery",
                        max_length=20,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Image",
                "verbose_name_plural": "Project Images",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("role", models.CharField(blank=True, max_length=120)),
                ("company", models.CharField(blank=True, max_length=120)),
                ("quote", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testimonials",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["order"],
            },
        ),
    ]
