# Generated by Django 5.2.12 on 2026-03-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('intro', models.TextField(blank=True, help_text='Short intro paragraph shown at the top of the About page.')),
                ('biography', models.TextField(blank=True)),
                ('philosophy', models.TextField(blank=True)),
                ('credentials', models.TextField(blank=True, help_text='Education, certifications, memberships — one per line.')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='about/cv/')),
            ],
            options={
                'verbose_name': 'About Profile',
                'verbose_name_plural': 'About Profile',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('who_for', models.CharField(blank=True, max_length=250)),
                ('value_proposition', models.TextField(blank=True)),
                ('deliverables', models.TextField(blank=True, help_text='One deliverable per line.')),
                ('icon_name', models.CharField(blank=True, help_text="Optional icon identifier (e.g. 'pen-ruler', 'building').", max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Jeannot Tsirenge', max_length=120)),
                ('tagline', models.CharField(default='Architectural design shaped by context, clarity, and identity.', max_length=220)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('contact_email', models.EmailField(default='contact@jeannot-tsirenge.com', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('behance_url', models.URLField(blank=True, help_text='Behance profile URL.')),
                ('issuu_url', models.URLField(blank=True, help_text='Issuu profile or publication URL.')),
                ('og_image', models.ImageField(blank=True, help_text='Default image used when sharing pages that have no cover image.', null=True, upload_to='site/')),
                ('meta_description', models.CharField(blank=True, help_text='Default meta description (homepage and fallback). Keep under 160 characters.', max_length=160)),
                ('about_meta_description', models.CharField(blank=True, help_text='Meta description for the About page. Keep under 160 characters.', max_length=160)),
                ('services_meta_description', models.CharField(blank=True, help_text='Meta description for the Services page. Keep under 160 characters.', max_length=160)),
                ('projects_meta_description', models.CharField(blank=True, help_text='Meta description for the Projects list page. Keep under 160 characters.', max_length=160)),
                ('contact_meta_description', models.CharField(blank=True, help_text='Meta description for the Contact page. Keep under 160 characters.', max_length=160)),
                ('google_analytics_id', models.CharField(blank=True, help_text='GA4 Measurement ID, e.g. G-XXXXXXXXXX.', max_length=30)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
