# Generated by Django 5.2.12 on 2026-03-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinquiry",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes for admin workflow — not visible to the client.",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="projectimage",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Descriptive alt text for screen readers. Falls back to caption if empty.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="behance_url",
            field=models.URLField(blank=True, help_text="Behance profile URL."),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="issuu_url",
            field=models.URLField(blank=True, help_text="Issuu profile or publication URL."),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="Default image used when sharing pages that have no cover image.",
                null=True,
                upload_to="site/",
            ),
        ),
    ]
