# Generated by Django 5.2.12 on 2026-03-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_sitesettings_per_page_meta_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='alt_text',
            field=models.CharField(blank=True, default='', help_text='Descriptive alt text for screen readers. Falls back to caption if empty.', max_length=200),
        ),
    ]
